// Eryn's seeded posture routines — data only.
// These are written to localStorage on first run and can be edited in-app.

export const PRESET_GROUPS = [
  {
    id: "group-upper-body",
    name: "Upper Body",
    pinned: true,
    collapsed: false,
  },
  {
    id: "group-lower-body",
    name: "Lower Body",
    pinned: true,
    collapsed: false,
  },
  {
    id: "group-strength",
    name: "Strength",
    pinned: true,
    collapsed: false,
  },
];

export const PRESET_ROUTINES = [
  {
    id: "preset-neck-retraction",
    groupId: "group-upper-body",
    name: "Neck Retraction",
    note: "Band, very light",
    repeat: 1,
    exercises: [
      {
        id: "ex-neck-ret",
        name: "Neck Retraction",
        type: "reps",
        load: "Very light band",
        sets: 3,
        repTarget: 8,
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 30,
        cue: "Stop if SCM bulges or throat strains.",
      },
    ],
  },
  {
    id: "preset-chin-tuck",
    groupId: "group-upper-body",
    name: "Chin-Tuck Reps",
    note: "No equipment",
    repeat: 1,
    exercises: [
      {
        id: "ex-chin-tuck",
        name: "Chin Tuck",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: 10,
        tempo: { out: 2, hold: 2, return: 2 },
        rest: 20,
        cue: "Backward glide to skull–spine concave, hold, release. It's a rep — train then relax.",
      },
    ],
  },
  {
    id: "preset-deadlift",
    groupId: "group-lower-body",
    name: "RDLs",
    note: "Door-anchored band",
    startCountdown: 15,
    repeat: 1,
    exercises: [
      {
        id: "ex-deadlift",
        name: "RDLs",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: 12,
        tempo: { out: 2, hold: 0, return: 3 },
        rest: 60,
        cue: "Start hinged. Stand tall against the band, squeeze glutes for the hold, then hinge back slowly with a neutral spine.",
      },
    ],
  },
  {
    id: "preset-leg-kickback",
    groupId: "group-lower-body",
    name: "Leg Kickback",
    note: "Band or cable",
    repeat: 1,
    exercises: [
      {
        id: "ex-leg-kickback",
        name: "Leg Kickback",
        type: "reps",
        load: "Band or cable",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep your pelvis level and ribs down. Drive the leg back from the glute, then return slowly without arching your lower back.",
      },
    ],
  },
  {
    id: "preset-bulgarian-squat",
    groupId: "group-lower-body",
    name: "Bulgarian Squat",
    note: "Rear-foot elevated",
    repeat: 1,
    exercises: [
      {
        id: "ex-bulgarian-squat-left",
        name: "Bulgarian Squat — Left",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: 12,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Keep the front foot planted and knee tracking over the toes. Lower under control, then drive through the whole foot.",
      },
      {
        id: "ex-bulgarian-squat-right",
        name: "Bulgarian Squat — Right",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: 12,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Keep the front foot planted and knee tracking over the toes. Lower under control, then drive through the whole foot.",
      },
    ],
  },
  {
    id: "preset-glute-screen-break",
    groupId: "group-lower-body",
    name: "Glute Activation",
    startCountdown: 10,
    note: "Foam roller + wall",
    repeat: 1,
    exercises: [
      {
        id: "ex-glute-break-hip-circles",
        name: "Quadruped Hip Circles",
        type: "reps",
        load: null,
        sets: 4,
        labels: [
          "Left • Forward",
          "Left • Backward",
          "Right • Forward",
          "Right • Backward",
        ],
        repTarget: 3,
        tempo: { out: 2, hold: 0, return: 2 },
        rest: 2,
        cue: "Move from the hip socket. Keep your pelvis and low back quiet.",
      },
      {
        id: "ex-glute-break-step-over",
        name: "Standing Roller Step-Over",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: 5,
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 2,
        cue: "Lift from the hip, clear the roller slowly, and keep your pelvis level.",
      },
      {
        id: "ex-glute-break-hip-hinge",
        name: "Roller-Supported Single-Leg Hip Hinge",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: 6,
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 2,
        cue: "Keep a tripod foot and soft knee. Hinge from the standing hip.",
      },
      {
        id: "ex-glute-break-hip-airplane",
        name: "Roller-Supported Hip Airplane",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: 4,
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 2,
        cue: "Rotate your pelvis around the planted hip. Use the roller only for light support.",
      },
    ],
  },
  {
    id: "preset-hip-glute-activation",
    groupId: "group-lower-body",
    name: "Hip & Glute Activation",
    note: "~13 min • Foam roller + wall",
    repeat: 1,
    exercises: [
      {
        id: "ex-hip-glute-worlds-greatest-stretch",
        name: "World's Greatest Stretch",
        type: "reps",
        load: null,
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: 3,
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 5,
        cue: "Keep the front foot planted and rotate through your upper trunk.",
      },
      {
        id: "ex-hip-glute-hip-circles",
        name: "Quadruped Hip Circles",
        type: "reps",
        load: null,
        sets: 4,
        labels: [
          "Left • Forward",
          "Left • Backward",
          "Right • Forward",
          "Right • Backward",
        ],
        repTarget: 5,
        tempo: { out: 2, hold: 0, return: 2 },
        rest: 2,
        cue: "Move from the hip socket. Keep your pelvis and low back quiet.",
      },
      {
        id: "ex-hip-glute-frog-rocks",
        name: "Frog Rocks",
        type: "reps",
        load: null,
        sets: 1,
        repTarget: 8,
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 5,
        cue: "Use a comfortable range. Keep your knees aligned and do not force the groin stretch.",
      },
      {
        id: "ex-hip-glute-step-over",
        name: "Standing Roller Step-Over",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: 6,
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 5,
        cue: "Lift from the hip, clear the roller slowly, and keep your pelvis level.",
      },
      {
        id: "ex-hip-glute-hip-hinge",
        name: "Roller-Supported Single-Leg Hip Hinge",
        type: "reps",
        load: "Foam roller + wall",
        sets: 4,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
        ],
        repTarget: 8,
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 10,
        cue: "Keep a tripod foot and soft knee. Hinge from the standing hip.",
      },
      {
        id: "ex-hip-glute-hip-airplane",
        name: "Roller-Supported Hip Airplane",
        type: "reps",
        load: "Foam roller + wall",
        sets: 4,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
        ],
        repTarget: 6,
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 10,
        cue: "Rotate your pelvis around the planted hip. Use the roller only for light support.",
      },
      {
        id: "ex-hip-glute-bridge",
        name: "Glute Bridge",
        type: "reps",
        load: null,
        sets: 1,
        repTarget: 8,
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 0,
        cue: "Lift through hip extension without arching your low back.",
      },
    ],
  },
  {
    id: "preset-tricep-pulldown",
    groupId: "group-upper-body",
    name: "Tricep Pulldown",
    note: "Door-anchored band",
    repeat: 1,
    exercises: [
      {
        id: "ex-tricep-pulldown",
        name: "Tricep Pulldown",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep elbows close to your sides. Press down to straight arms, hold, then return slowly without letting shoulders rise.",
      },
    ],
  },
  {
    id: "preset-single-side-tricep-extension",
    groupId: "group-upper-body",
    name: "Single-Side Tricep Extension",
    note: "Door-anchored band • both sides",
    repeat: 1,
    exercises: [
      {
        id: "ex-single-side-tricep-extension-left",
        name: "Single-Side Tricep Extension — Left",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep the upper arm still. Extend to a straight elbow, hold, then return slowly.",
      },
      {
        id: "ex-single-side-tricep-extension-right",
        name: "Single-Side Tricep Extension — Right",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep the upper arm still. Extend to a straight elbow, hold, then return slowly.",
      },
    ],
  },
  {
    id: "preset-workout-a",
    groupId: "group-strength",
    name: "Workout A — Hinge + Pull",
    note: "Low Anchor",
    repeat: 1,
    exercises: [
      {
        id: "ex-wa-rdl",
        name: "Single-Leg Band RDL",
        type: "reps",
        load: "Band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 20,
        cue: "Hinge from the standing hip, keep a soft knee and neutral spine. Squeeze the glute at the top.",
      },
      {
        id: "ex-wa-row",
        name: "Door-Anchored Band Row",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 60,
        cue: "Retract the shoulder blade, pull the elbow back, hold, then return slowly without letting the shoulder creep forward.",
      },
      {
        id: "ex-wa-split-squat",
        name: "Supported Split Squat",
        type: "reps",
        load: null,
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Keep the front knee tracking over the toes. Lower under control and drive through the whole front foot.",
      },
      {
        id: "ex-wa-chest-press",
        name: "Band Chest Press",
        type: "reps",
        load: "Band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 60,
        cue: "Press straight out to full extension, hold, then return slowly with control.",
      },
      {
        id: "ex-wa-hip-abduction",
        name: "Standing Band Hip Abduction",
        type: "reps",
        load: "Band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 30,
        cue: "Stand tall. Lift the leg to the side from the hip, hold briefly, then return slowly.",
      },
      {
        id: "ex-wa-march",
        name: "Standing Resisted March",
        type: "reps",
        load: "Band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 1, hold: 1, return: 1 },
        rest: 30,
        cue: "Drive the knee up against the band, hold at the top, then lower with control. Keep the pelvis level.",
      },
    ],
  },
  {
    id: "preset-workout-c",
    groupId: "group-strength",
    name: "Workout C — High Anchor",
    note: "Low anchor + slant board",
    repeat: 1,
    exercises: [
      {
        id: "ex-wc-slant-squat",
        name: "Slant-Board Squat",
        type: "reps",
        load: "Slant board",
        sets: 3,
        repTarget: 15,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 60,
        cue: "Drive the knees forward over the toes. Focus on high knee-extension demand through the quads.",
      },
      {
        id: "ex-wc-reverse-lunge",
        name: "Reverse Lunge",
        type: "reps",
        load: null,
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 3, hold: 0, return: 2 },
        rest: 45,
        cue: "Step back under control, keep the front knee tracking the toes. Drive through the whole front foot to return.",
      },
      {
        id: "ex-wc-lat-pulldown",
        name: "Single-Arm Lat Pulldown",
        type: "reps",
        load: "High-anchor band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 30,
        cue: "Initiate with the lat. Pull the elbow down and back, hold, then return slowly.",
      },
      {
        id: "ex-wc-ha-row",
        name: "High-Anchor Single-Arm Row",
        type: "reps",
        load: "High-anchor band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 30,
        cue: "Row the elbow toward your hip. Squeeze the mid-back and rear delt at end range, then return slowly.",
      },
      {
        id: "ex-wc-tricep-pressdown",
        name: "Single-Arm Triceps Pressdown",
        type: "reps",
        load: "High-anchor band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 30,
        cue: "Keep the upper arm still. Press to full elbow extension, hold, then return slowly.",
      },
      {
        id: "ex-wc-tricep-oh",
        name: "Overhead Band Triceps Extension",
        type: "reps",
        load: "Band",
        sets: 3,
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 60,
        cue: "Keep the elbows close and pointed up. Extend to lockout, hold, then return slowly for a full long-head stretch.",
      },
    ],
  },
  {
    id: "preset-workout-d",
    groupId: "group-strength",
    name: "Workout D — Inner Thigh + Knee",
    note: "Low anchor + slant board + sliders",
    repeat: 1,
    exercises: [
      {
        id: "ex-wd-slant-squat",
        name: "Slant-Board Squat",
        type: "reps",
        load: "Slant board",
        sets: 3,
        repTarget: 15,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 60,
        cue: "Drive the knees forward over the toes. Focus on VMO activation through the quad.",
      },
      {
        id: "ex-wd-lateral-lunge",
        name: "Slider Lateral Lunge",
        type: "reps",
        load: "Slider",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 3, hold: 0, return: 2 },
        rest: 45,
        cue: "Slide the foot out with control, load the adductor, then pull back to start. Keep the standing knee stable.",
      },
      {
        id: "ex-wd-reverse-lunge",
        name: "Slider Reverse Lunge",
        type: "reps",
        load: "Slider",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 12,
        tempo: { out: 3, hold: 0, return: 2 },
        rest: 45,
        cue: "Slide the foot back under control. Keep the front knee tracking the toes and drive through the whole front foot to return.",
      },
      {
        id: "ex-wd-step-down",
        name: "Supported Low Step-Down",
        type: "reps",
        load: null,
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 10,
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Tripod foot → gentle short-foot → soft knee → 2–3 sec descent. Stop before the arch collapses or knee dives inward. Use hand support as needed.",
      },
      {
        id: "ex-wd-hip-adduction",
        name: "Standing Band Hip Adduction",
        type: "reps",
        load: "Band",
        sets: 6,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
          "Left • Round 3",
          "Right • Round 3",
        ],
        repTarget: 15,
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 30,
        cue: "Stand tall. Pull the leg across your body from the inner thigh, hold, then return slowly.",
      },
      {
        id: "ex-wd-adductor-squeeze",
        name: "Pilates-Ball Adductor Squeeze",
        type: "reps",
        load: "Pilates ball",
        sets: 2,
        repTarget: 1,
        tempo: { out: 0, hold: 25, return: 0 },
        rest: 30,
        cue: "Place the ball between your inner thighs. Squeeze and hold for 20–30 seconds. Breathe steadily throughout.",
      },
    ],
  },
  {
    id: "preset-fuller-break",
    name: "Fuller Break",
    note: "~8–10 min",
    repeat: 1,
    exercises: [
      {
        id: "ex-fb-pull-aparts",
        name: "Pull-Aparts",
        type: "reps",
        load: "10 lb",
        sets: 2,
        repTarget: 15,
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
      {
        id: "ex-fb-face-pulls",
        name: "Face Pulls",
        type: "reps",
        load: "15 lb",
        sets: 2,
        repTarget: 15,
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
    ],
  },
];
