// Eryn's seeded posture routines — data only.
// These are written to localStorage on first run and can be edited in-app.

export const PRESET_GROUPS = [
  {
    id: 'group-upper-body',
    name: 'Upper Body',
    pinned: true,
    collapsed: false,
  },
  {
    id: 'group-lower-body',
    name: 'Lower Body',
    pinned: true,
    collapsed: false,
  },
];

export const PRESET_ROUTINES = [
  {
    id: 'preset-neck-retraction',
    groupId: 'group-upper-body',
    name: 'Neck Retraction',
    note: 'Band, very light',
    repeat: 1,
    exercises: [
      {
        id: 'ex-neck-ret',
        name: 'Neck Retraction',
        type: 'reps',
        load: 'Very light band',
        sets: 3,
        repTarget: [8, 8],
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 30,
        cue: 'Stop if SCM bulges or throat strains.',
      },
    ],
  },
  {
    id: 'preset-chin-tuck',
    groupId: 'group-upper-body',
    name: 'Chin-Tuck Reps',
    note: 'No equipment',
    repeat: 1,
    exercises: [
      {
        id: 'ex-chin-tuck',
        name: 'Chin Tuck',
        type: 'reps',
        load: null,
        sets: 3,
        repTarget: [10, 10],
        tempo: { out: 2, hold: 2, return: 2 },
        rest: 20,
        cue: "Backward glide to skull–spine concave, hold, release. It's a rep — train then relax.",
      },
    ],
  },
  {
    id: 'preset-deadlift',
    groupId: 'group-lower-body',
    name: 'Deadlift & Pull-Through',
    note: '3 exercises • 25 lb',
    repeat: 1,
    exercises: [
      {
        id: 'ex-deadlift',
        name: 'Deadlift',
        type: 'reps',
        load: '25 lb',
        sets: 3,
        repTarget: [12, 12],
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 60,
        cue: 'Keep back flat, drive through heels, and squeeze glutes at the top.',
      },
      {
        id: 'ex-pull-through',
        name: 'Cable Pull-Through',
        type: 'reps',
        load: '25 lb',
        sets: 3,
        repTarget: [12, 12],
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 45,
        cue: 'Reach back between legs, hinge at hips. Drive hips forward to stand, squeezing glutes at the top.',
      },
      {
        id: 'ex-hip-hinge-iso',
        name: 'Hip Hinge Isolation',
        type: 'reps',
        load: 'None',
        sets: 3,
        repTarget: [12, 12],
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 30,
        cue: 'Focus on pure hip-hinge mechanics. Stand tall, hinge back from hips with soft knees, hold the stretch, then stand.',
      },
    ],
  },
  {
    id: 'preset-fuller-break',
    name: 'Fuller Break',
    note: '~8–10 min',
    repeat: 1,
    exercises: [
      {
        id: 'ex-fb-pull-aparts',
        name: 'Pull-Aparts',
        type: 'reps',
        load: '10 lb',
        sets: 2,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
      {
        id: 'ex-fb-face-pulls',
        name: 'Face Pulls',
        type: 'reps',
        load: '15 lb',
        sets: 2,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
    ],
  },
  {
    id: 'preset-prone-cobra',
    name: 'Prone Cobra',
    note: 'Isometric hold',
    repeat: 1,
    exercises: [
      {
        id: 'ex-prone-cobra',
        name: 'Prone Cobra',
        type: 'hold',
        load: null,
        sets: 3,
        holdDuration: 25,
        rest: 30,
        cue: null,
      },
    ],
  },
];
