// Eryn's seeded posture routines — data only.
// These are written to localStorage on first run and can be edited in-app.

export const PRESET_GROUPS = [
  {
    id: "group-upper-body",
    name: "Upper Body",
    pinned: true,
    collapsed: false,
  },
  {
    id: "group-lower-body",
    name: "Lower Body",
    pinned: true,
    collapsed: false,
  },
];

export const PRESET_ROUTINES = [
  {
    id: "preset-neck-retraction",
    groupId: "group-upper-body",
    name: "Neck Retraction",
    note: "Band, very light",
    repeat: 1,
    exercises: [
      {
        id: "ex-neck-ret",
        name: "Neck Retraction",
        type: "reps",
        load: "Very light band",
        sets: 3,
        repTarget: [8, 8],
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 30,
        cue: "Stop if SCM bulges or throat strains.",
      },
    ],
  },
  {
    id: "preset-chin-tuck",
    groupId: "group-upper-body",
    name: "Chin-Tuck Reps",
    note: "No equipment",
    repeat: 1,
    exercises: [
      {
        id: "ex-chin-tuck",
        name: "Chin Tuck",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: [10, 10],
        tempo: { out: 2, hold: 2, return: 2 },
        rest: 20,
        cue: "Backward glide to skull–spine concave, hold, release. It's a rep — train then relax.",
      },
    ],
  },
  {
    id: "preset-deadlift",
    groupId: "group-lower-body",
    name: "RDLs",
    note: "Door-anchored band",
    repeat: 1,
    exercises: [
      {
        id: "ex-deadlift",
        name: "RDLs",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: [12, 12],
        tempo: { out: 2, hold: 0, return: 3 },
        rest: 60,
        cue: "Start hinged. Stand tall against the band, squeeze glutes for the hold, then hinge back slowly with a neutral spine.",
      },
    ],
  },
  {
    id: "preset-leg-kickback",
    groupId: "group-lower-body",
    name: "Leg Kickback",
    note: "Band or cable",
    repeat: 1,
    exercises: [
      {
        id: "ex-leg-kickback",
        name: "Leg Kickback",
        type: "reps",
        load: "Band or cable",
        sets: 3,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep your pelvis level and ribs down. Drive the leg back from the glute, then return slowly without arching your lower back.",
      },
    ],
  },
  {
    id: "preset-bulgarian-squat",
    groupId: "group-lower-body",
    name: "Bulgarian Squat",
    note: "Rear-foot elevated",
    repeat: 1,
    exercises: [
      {
        id: "ex-bulgarian-squat-left",
        name: "Bulgarian Squat — Left",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: [8, 12],
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Keep the front foot planted and knee tracking over the toes. Lower under control, then drive through the whole foot.",
      },
      {
        id: "ex-bulgarian-squat-right",
        name: "Bulgarian Squat — Right",
        type: "reps",
        load: null,
        sets: 3,
        repTarget: [8, 12],
        tempo: { out: 3, hold: 1, return: 2 },
        rest: 45,
        cue: "Keep the front foot planted and knee tracking over the toes. Lower under control, then drive through the whole foot.",
      },
    ],
  },
  {
    id: "preset-glute-screen-break",
    groupId: "group-lower-body",
    name: "Glute Activation",
    note: "Foam roller + wall",
    repeat: 1,
    exercises: [
      {
        id: "ex-glute-break-hip-circles",
        name: "Quadruped Hip Circles",
        type: "reps",
        load: null,
        sets: 4,
        labels: [
          "Left • Forward",
          "Left • Backward",
          "Right • Forward",
          "Right • Backward",
        ],
        repTarget: [3, 3],
        tempo: { out: 2, hold: 0, return: 2 },
        rest: 2,
        cue: "Move from the hip socket. Keep your pelvis and low back quiet.",
      },
      {
        id: "ex-glute-break-step-over",
        name: "Standing Roller Step-Over",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: [5, 5],
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 2,
        cue: "Lift from the hip, clear the roller slowly, and keep your pelvis level.",
      },
      {
        id: "ex-glute-break-hip-hinge",
        name: "Roller-Supported Single-Leg Hip Hinge",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: [6, 6],
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 2,
        cue: "Keep a tripod foot and soft knee. Hinge from the standing hip.",
      },
      {
        id: "ex-glute-break-hip-airplane",
        name: "Roller-Supported Hip Airplane",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: [4, 4],
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 2,
        cue: "Rotate your pelvis around the planted hip. Use the roller only for light support.",
      },
    ],
  },
  {
    id: "preset-hip-glute-activation",
    groupId: "group-lower-body",
    name: "Hip & Glute Activation",
    note: "~13 min • Foam roller + wall",
    repeat: 1,
    exercises: [
      {
        id: "ex-hip-glute-worlds-greatest-stretch",
        name: "World's Greatest Stretch",
        type: "reps",
        load: null,
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: [3, 3],
        tempo: { out: 3, hold: 2, return: 3 },
        rest: 5,
        cue: "Keep the front foot planted and rotate through your upper trunk.",
      },
      {
        id: "ex-hip-glute-hip-circles",
        name: "Quadruped Hip Circles",
        type: "reps",
        load: null,
        sets: 4,
        labels: [
          "Left • Forward",
          "Left • Backward",
          "Right • Forward",
          "Right • Backward",
        ],
        repTarget: [5, 5],
        tempo: { out: 2, hold: 0, return: 2 },
        rest: 2,
        cue: "Move from the hip socket. Keep your pelvis and low back quiet.",
      },
      {
        id: "ex-hip-glute-frog-rocks",
        name: "Frog Rocks",
        type: "reps",
        load: null,
        sets: 1,
        repTarget: [8, 8],
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 5,
        cue: "Use a comfortable range. Keep your knees aligned and do not force the groin stretch.",
      },
      {
        id: "ex-hip-glute-step-over",
        name: "Standing Roller Step-Over",
        type: "reps",
        load: "Foam roller + wall",
        sets: 2,
        labels: ["Left", "Right"],
        repTarget: [6, 6],
        tempo: { out: 2, hold: 1, return: 2 },
        rest: 5,
        cue: "Lift from the hip, clear the roller slowly, and keep your pelvis level.",
      },
      {
        id: "ex-hip-glute-hip-hinge",
        name: "Roller-Supported Single-Leg Hip Hinge",
        type: "reps",
        load: "Foam roller + wall",
        sets: 4,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
        ],
        repTarget: [8, 8],
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 10,
        cue: "Keep a tripod foot and soft knee. Hinge from the standing hip.",
      },
      {
        id: "ex-hip-glute-hip-airplane",
        name: "Roller-Supported Hip Airplane",
        type: "reps",
        load: "Foam roller + wall",
        sets: 4,
        labels: [
          "Left • Round 1",
          "Right • Round 1",
          "Left • Round 2",
          "Right • Round 2",
        ],
        repTarget: [6, 6],
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 10,
        cue: "Rotate your pelvis around the planted hip. Use the roller only for light support.",
      },
      {
        id: "ex-hip-glute-bridge",
        name: "Glute Bridge",
        type: "reps",
        load: null,
        sets: 1,
        repTarget: [8, 8],
        tempo: { out: 3, hold: 1, return: 3 },
        rest: 0,
        cue: "Lift through hip extension without arching your low back.",
      },
    ],
  },
  {
    id: "preset-tricep-pulldown",
    groupId: "group-upper-body",
    name: "Tricep Pulldown",
    note: "Door-anchored band",
    repeat: 1,
    exercises: [
      {
        id: "ex-tricep-pulldown",
        name: "Tricep Pulldown",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep elbows close to your sides. Press down to straight arms, hold, then return slowly without letting shoulders rise.",
      },
    ],
  },
  {
    id: "preset-single-side-tricep-extension",
    groupId: "group-upper-body",
    name: "Single-Side Tricep Extension",
    note: "Door-anchored band • both sides",
    repeat: 1,
    exercises: [
      {
        id: "ex-single-side-tricep-extension-left",
        name: "Single-Side Tricep Extension — Left",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep the upper arm still. Extend to a straight elbow, hold, then return slowly.",
      },
      {
        id: "ex-single-side-tricep-extension-right",
        name: "Single-Side Tricep Extension — Right",
        type: "reps",
        load: "Door-anchored band",
        sets: 3,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 1, return: 3 },
        rest: 40,
        cue: "Keep the upper arm still. Extend to a straight elbow, hold, then return slowly.",
      },
    ],
  },
  {
    id: "preset-fuller-break",
    name: "Fuller Break",
    note: "~8–10 min",
    repeat: 1,
    exercises: [
      {
        id: "ex-fb-pull-aparts",
        name: "Pull-Aparts",
        type: "reps",
        load: "10 lb",
        sets: 2,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
      {
        id: "ex-fb-face-pulls",
        name: "Face Pulls",
        type: "reps",
        load: "15 lb",
        sets: 2,
        repTarget: [12, 15],
        tempo: { out: 2, hold: 2, return: 3 },
        rest: 40,
        cue: null,
      },
    ],
  },
  {
    id: "preset-prone-cobra",
    name: "Prone Cobra",
    note: "Isometric hold",
    repeat: 1,
    exercises: [
      {
        id: "ex-prone-cobra",
        name: "Prone Cobra",
        type: "hold",
        load: null,
        sets: 3,
        holdDuration: 25,
        rest: 30,
        cue: null,
      },
    ],
  },
];
